canciones = [
    {"song": "Billie Jean", "artist": "Michael Jackson", "album": "Thriller"},
    {"song": "Like a Prayer", "artist": "Madonna", "album": "Like a Prayer"},
    {"song": "Sweet Child O' Mine", "artist": "Guns N' Roses", "album": "Appetite for Destruction"},
    {"song": "Every Breath You Take", "artist": "The Police", "album": "Synchronicity"},
    {"song": "Take On Me", "artist": "a-ha", "album": "Hunting High and Low"},
    {"song": "With or Without You", "artist": "U2", "album": "The Joshua Tree"},
    {"song": "Livin' on a Prayer", "artist": "Bon Jovi", "album": "Slippery When Wet"},
    {"song": "Smells Like Teen Spirit", "artist": "Nirvana", "album": "Nevermind"},
    {"song": "Wonderwall", "artist": "Oasis", "album": "(What's the Story) Morning Glory?"},
    {"song": "Creep", "artist": "Radiohead", "album": "Pablo Honey"},
    {"song": "La Flaca", "artist": "Jarabe de Palo", "album": "La Flaca"},
    {"song": "Rayando el Sol", "artist": "Maná", "album": "Falta Amor"},
    {"song": "De Música Ligera", "artist": "Soda Stereo", "album": "Canción Animal"},
    {"song": "Persiana Americana", "artist": "Soda Stereo", "album": "Signos"},
    {"song": "Lamento Boliviano", "artist": "Enanitos Verdes", "album": "Big Bang"},
    {"song": "Matador", "artist": "Los Fabulosos Cadillacs", "album": "Vasos Vacíos"},
    {"song": "Corazón Espinado", "artist": "Santana ft. Maná", "album": "Supernatural"},
    {"song": "Oye Mi Amor", "artist": "Maná", "album": "¿Dónde Jugarán los Niños?"},
    {"song": "Entre Dos Tierras", "artist": "Héroes del Silencio", "album": "Senderos de Traición"},
    {"song": "Nada Valgo Sin Tu Amor", "artist": "Juanes", "album": "Mi Sangre"},
    {"song": "Hips Don't Lie", "artist": "Shakira ft. Wyclef Jean", "album": "Oral Fixation, Vol. 2"},
    {"song": "Whenever, Wherever", "artist": "Shakira", "album": "Laundry Service"},
    {"song": "Gasolina", "artist": "Daddy Yankee", "album": "Barrio Fino"},
    {"song": "Danza Kuduro", "artist": "Don Omar", "album": "Meet the Orphans"},
    {"song": "La Camisa Negra", "artist": "Juanes", "album": "Mi Sangre"},
    {"song": "Umbrella", "artist": "Rihanna", "album": "Good Girl Gone Bad"},
    {"song": "Single Ladies", "artist": "Beyoncé", "album": "I Am... Sasha Fierce"},
    {"song": "Poker Face", "artist": "Lady Gaga", "album": "The Fame"},
    {"song": "Rolling in the Deep", "artist": "Adele", "album": "21"},
    {"song": "Hey Ya!", "artist": "OutKast", "album": "Speakerboxxx/The Love Below"},
    {"song": "In the End", "artist": "Linkin Park", "album": "Hybrid Theory"},
    {"song": "Numb", "artist": "Linkin Park", "album": "Meteora"},
    {"song": "Boulevard of Broken Dreams", "artist": "Green Day", "album": "American Idiot"},
    {"song": "American Idiot", "artist": "Green Day", "album": "American Idiot"},
    {"song": "Mr. Brightside", "artist": "The Killers", "album": "Hot Fuss"},
    {"song": "Clocks", "artist": "Coldplay", "album": "A Rush of Blood to the Head"},
    {"song": "Fix You", "artist": "Coldplay", "album": "X&Y"},
    {"song": "Yellow", "artist": "Coldplay", "album": "Parachutes"},
    {"song": "Lose Yourself", "artist": "Eminem", "album": "Curtain Call: The Hits"},
    {"song": "Stan", "artist": "Eminem", "album": "The Marshall Mathers LP"},
    {"song": "Without Me", "artist": "Eminem", "album": "The Eminem Show"},
    {"song": "I Gotta Feeling", "artist": "Black Eyed Peas", "album": "The E.N.D."},
    {"song": "Where Is the Love?", "artist": "Black Eyed Peas", "album": "Elephunk"},
    {"song": "Toxic", "artist": "Britney Spears", "album": "In the Zone"},
    {"song": "Baby One More Time", "artist": "Britney Spears", "album": "...Baby One More Time"},
    {"song": "Genie in a Bottle", "artist": "Christina Aguilera", "album": "Christina Aguilera"},
    {"song": "Complicated", "artist": "Avril Lavigne", "album": "Let Go"},
    {"song": "Sk8er Boi", "artist": "Avril Lavigne", "album": "Let Go"},
    {"song": "Viva La Vida", "artist": "Coldplay", "album": "Viva la Vida or Death and All His Friends"},
    {"song": "Feel Good Inc.", "artist": "Gorillaz", "album": "Demon Days"}
]